#!/bin/sh
docker run  \
   -v /etc/localtime:/etc/localtime:ro \
   -v /tmp/.X11-unix:/tmp/.X11-unix \
   -e DISPLAY=unix$DISPLAY \
   -i \
   --rm \
   --device /dev/snd:/dev/snd \
   -v ${HOME}/.spotify/config:/home/spotify/.config/spotify \
   -v ${HOME}/.spotify/cache:/home/spotify/.cache/spotify \
    -v /var/lib/dbus:/var/lib/dbus \
   --name spotify \
   jess/spotify
