#!/bin/sh
set -e

BASE=gianarb-ovpn
PID_FILE=/var/run/$BASE.pid
SSD_PIDFILE=/var/run/$BASE-ssd.pid
LOGFILE=/var/log/$BASE.log
OPENVPN_OPT=/home/gianarb/.config/openvpn/gianarb.ovpn
OPENVPN_BIN=/usr/sbin/openvpn

# Get lsb functions
. /lib/lsb/init-functions

fail_unless_root() {
	if [ "$(id -u)" != '0' ]; then
		log_failure_msg "$BASE must be run as root"
		exit 1
	fi
}

case "$1" in
	start)
		log_begin_msg "Starting openvpn with GianArb configuration"
        fail_unless_root
		start-stop-daemon --start --background \
			--no-close \
			--exec "$OPENVPN_BIN" \
			--pidfile "$SSD_PIDFILE" \
			--make-pidfile \
			-- \
                $OPENVPN_OPT >> "$LOGFILE" 2>&1
		log_end_msg $?
		;;

	stop)
		log_begin_msg "Stopping openvpn with GianArb configuration"
		start-stop-daemon --stop --pidfile "$SSD_PIDFILE" --retry 10
		log_end_msg $?
		;;

	restart)
		fail_unless_root
		pid=`cat "$SSD_PIDFILE" 2>/dev/null`
		[ -n "$pid" ] \
			&& ps -p $pid > /dev/null 2>&1 \
			&& $0 stop
		$0 start
		;;

	force-reload)
		fail_unless_root
		$0 restart
		;;

	status)
		status_of_proc -p "$SSD_PIDFILE" "$OPENVPN_BIN"
		;;

	*)
		echo "Usage: service docker {start|stop|restart|status}"
		exit 1
		;;
esac
